name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint with ShellCheck
        run: shellcheck setup_user.sh

  bats_tests:
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - uses: actions/checkout@v3
      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats-core
      - name: Run BATS tests
        run: bats tests/setup_user.bats
